# Generated by Django 3.2.8 on 2021-10-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookmodel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='data',
        ),
    ]
