# Generated by Django 3.2.8 on 2021-10-14 18:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
