# Generated by Django 3.2.8 on 2021-10-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookmodel_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='json',
            field=models.JSONField(default=None),
        ),
    ]
